apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  labels:
    foo: bar
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /c/Users/<USERNAME>/Projects/redis-cluster-example/mnt/redis-data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-data
  namespace: redis-cluster-example
  labels:
    foo: bar
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 8Gi
  volumeName: redis-data